name: Build cld3 wheels (Windows only)

on: [push, pull_request, workflow_dispatch]

jobs:
  wheel:
    name: windows-wheel
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # для запуска cibuildwheel

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Install Protobuf
        run: |
          vcpkg integrate install
          vcpkg install protobuf:x64-windows
        shell: pwsh

      - name: Build wheels
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"
          CIBW_PRERELEASE_PYTHONS: "True"
          CIBW_SKIP: "*-win32"
          CIBW_ENVIRONMENT_WINDOWS: >
            PROTOC="C:/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe"
            INCLUDE="C:/vcpkg/installed/x64-windows/include"
            LIB="C:/vcpkg/installed/x64-windows/lib"
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: windows-wheels
          path: wheelhouse/*.whl
