name: Build cld3 wheel (Windows, Python 3.14 only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # позволяет запускать вручную

jobs:
  wheel:
    name: cp314-win_amd64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Установить Python (для запуска cibuildwheel)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Установить cibuildwheel
        run: pip install cibuildwheel

      - name: Установить Protobuf
        run: |
          vcpkg install protobuf:x64-windows
        shell: pwsh

      - name: Собрать wheel
        env:
          CIBW_BUILD: "cp314-*"
          CIBW_PRERELEASE_PYTHONS: "True"
          CIBW_SKIP: "*-win32"
          CIBW_ENVIRONMENT_WINDOWS: >
            Protobuf_ROOT="C:/vcpkg/installed/x64-windows"
            CMAKE_PREFIX_PATH="C:/vcpkg/installed/x64-windows"
            PROTOC="C:/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe"
            INCLUDE="C:/vcpkg/installed/x64-windows/include"
            LIB="C:/vcpkg/installed/x64-windows/lib"
            PATH="$env:PATH;C:/vcpkg/installed/x64-windows/tools/protobuf"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Загрузить артефакт
        uses: actions/upload-artifact@v4
        with:
          name: cld3-cp314-win_amd64
          path: wheelhouse/*.whl
